/**
 * Created by shipengqi on 17-1-11.
 */

//线上   列表显示样式-block_id
const ONLINE_BLOCK_ID_GLOBAL_TOP = 0;
const ONLINE_BLOCK_ID_BIG_ADVERT = 1;
const ONLINE_BLOCK_ID_SMALL_ADVERT = 2;
const ONLINE_BLOCK_ID_NO_IMAGE = 4;
const ONLINE_BLOCK_ID_SINGLE_IMAGE = 5;
const ONLINE_BLOCK_ID_MULTIPLE_IMAGE = 6;
const ONLINE_BLOCK_ID_START_ADVERT = 8;
const ONLINE_BLOCK_ID_JOKE = 9;
const ONLINE_BLOCK_ID_GIF_IMAGE = 10;
const ONLINE_BLOCK_ID_IMAGE_WORDS = 11;
const ONLINE_BLOCK_ID_VIDEO_CHANNEL = 16;
const ONLINE_BLOCK_ID_BEAUTY_CHANNEL = 17;
const ONLINE_BLOCK_ID_ACTIVITY = 18;
const ONLINE_BLOCK_ID_H5_ACTIVITY = 19;
const ONLINE_BLOCK_ID_VIDEO = 20;

//线上   文章类型-news_category
const ONLINE_CATERGORY_COMMON = 0;
const ONLINE_CATERGORY_SEMINAR = 1;
const ONLINE_CATERGORY_IMAGE = 2;
const ONLINE_CATERGORY_JOKE = 3;
const ONLINE_CATERGORY_VIDEO = 4;
const ONLINE_CATERGORY_BEAUTY = 5;
const ONLINE_CATERGORY_ACTIVITY = 6;
const ONLINE_CATERGORY_OUTSIDE_LINK = 7;
const ONLINE_CATERGORY_REVELATION = 8;
const ONLINE_CATERGORY_ADVERT = 9;
const ONLINE_CATERGORY_H5_ACTIVITY = 10;

//线上轮播类型
const ONLINE_SET_TOP_ARTICLE = 1;
const ONLINE_GLOBAL_ARTICLE = 2;

//线下   列表显示样式-block_id
const BLOCK_ID_NO_IMAGE = 1;
const BLOCK_ID_SINGLE_IMAGE = 2;
const BLOCK_ID_MULTIPLE_IMAGE = 3;
const BLOCK_ID_BIG_ADVERT = 4;
const BLOCK_ID_SMALL_ADVERT = 5;
const BLOCK_ID_VIDEO = 6;

//线下   普通文章类型-type
const NEWS_TYPE_COMMON = 1;
const NEWS_TYPE_IMAGE = 2;
const NEWS_TYPE_OUTSIDE_LINK = 3;
const NEWS_TYPE_VIDEO = 4;

//线下   文章category
const NEWS_CATEGORY_COMMON = 0;
const NEWS_CATEGORY_SEMINAR = 1;
const NEWS_CATEGORY_ACTIVITY = 2;
const NEWS_CATEGORY_H5_ACTIVITY = 3;
const NEWS_CATEGORY_REVELATION = 4;
const NEWS_CATEGORY_ADVERT = 5;

//线下   区块列表类型
const GLOBAL_TOP_NEWS_LIST = 1;
const TOP_NEWS_LIST = 2;
const SORT_NEWS_LIST = 3;
const COMMON_NEWS_LIST = 4;

const GLOBAL_TOP_NEWS_LIST_COUNT = 6;
const TOP_NEWS_LIST_COUNT = 3;
const SORT_NEWS_LIST_COUNT = 12;
const COMMON_NEWS_LIST_COUNT = 2;

const MATERIAL_LIST_COUNT = 10;

//列表方法类型
const AREA_NEWS_LIST = 0;

//cms　collection name prefix
const CMS_COLLECTION_NAME_PREFIX = 'handwork_';

const IS_HANDWORK_NEWS = 1;
const IS_NEWS = 1;

//线上频道id
const ONLINE_LOCAL_CHANNEL = 1;
const ONLINE_COUNTRY_CHANNEL = 2;

const ONLINE_LOCAL_TAG = -1;
const ONLINE_COUNTRY_TAG = 129;

//线下全国site_id
const COUNTRY_SITE_ID = 0;
const ONLINE_COUNTRY_REGION_ID = 999999;

const LOCAL_CHANNEL_TAG = 100;
const COUNTRY_CHANNEL_TAG = 101;


//图片类型
const NEWS_LIST_IMAGE = 1;
const NEWS_CONTENT_IMAGE = 0;

//线下 redis key
const REDIS_KEY_NEWS_DETAIL = 'article_detail:';
const REDIS_KEY_MATERIAL_LIST = 'material_list:';

//app redis key
const REDIS_KEY_ARTICLE_DETAIL = 'article:detail:';
const REDIS_KEY_GLOBAL_YOP_LIST = 'channel:scroll.news.ids:';
const REDIS_KEY_TOP_LIST = 'channel:top.news.ids:';
const REDIS_KEY_SORT_LIST = 'channel:stnews.ids:';


//redis expire time
const REDIS_EXPIRE_NEWS_DETAIL = 10 * 60;
const REDIS_EXPIRE_MATERIAL_LIST = 10 * 30;

//同步表线上文章状态
const SYNC_IS_ONLINE = 1;
const SYNC_NOT_ONLINE = 0;

//频道enum('country','commend')
const ENUM_COUNTRY_CHANNEL = 'country';
const ENUM_COMMEND_CHANNEL = 'commend';

//内容库列表choose默认值
const MATERIAL_LIST_CHOOSE_DEFAULT = 0;

//发布状态
const UN_PUBLISHED_ARTICLE = 0;
const PUBLISHED_ARTICLE = 1;

//推送
const PUSH_TO_USER = 'user';
const PUSH_TO_SITE = 'site';
const PUSH_TO_ALL = 'all';

export {
    IS_HANDWORK_NEWS,
    IS_NEWS,
    SYNC_IS_ONLINE,
    SYNC_NOT_ONLINE,
    ENUM_COUNTRY_CHANNEL,
    ENUM_COMMEND_CHANNEL,
    AREA_NEWS_LIST,
    ONLINE_BLOCK_ID_GLOBAL_TOP,
    ONLINE_BLOCK_ID_BIG_ADVERT,
    ONLINE_BLOCK_ID_SMALL_ADVERT,
    ONLINE_BLOCK_ID_NO_IMAGE,
    ONLINE_BLOCK_ID_SINGLE_IMAGE,
    ONLINE_BLOCK_ID_MULTIPLE_IMAGE,
    ONLINE_BLOCK_ID_START_ADVERT,
    ONLINE_BLOCK_ID_JOKE,
    ONLINE_BLOCK_ID_GIF_IMAGE,
    ONLINE_BLOCK_ID_IMAGE_WORDS,
    ONLINE_BLOCK_ID_VIDEO_CHANNEL,
    ONLINE_BLOCK_ID_BEAUTY_CHANNEL,
    ONLINE_BLOCK_ID_ACTIVITY,
    ONLINE_BLOCK_ID_H5_ACTIVITY,
    ONLINE_CATERGORY_COMMON,
    ONLINE_CATERGORY_SEMINAR,
    ONLINE_CATERGORY_IMAGE,
    ONLINE_CATERGORY_JOKE,
    ONLINE_CATERGORY_VIDEO,
    ONLINE_CATERGORY_BEAUTY,
    ONLINE_CATERGORY_ACTIVITY,
    ONLINE_CATERGORY_OUTSIDE_LINK,
    ONLINE_CATERGORY_REVELATION,
    ONLINE_CATERGORY_ADVERT,
    ONLINE_CATERGORY_H5_ACTIVITY,
    ONLINE_BLOCK_ID_VIDEO,
    ONLINE_LOCAL_TAG,
    ONLINE_COUNTRY_TAG,
    BLOCK_ID_BIG_ADVERT,
    BLOCK_ID_SMALL_ADVERT,
    BLOCK_ID_NO_IMAGE,
    BLOCK_ID_SINGLE_IMAGE,
    BLOCK_ID_MULTIPLE_IMAGE,
    BLOCK_ID_VIDEO,
    NEWS_TYPE_COMMON,
    NEWS_TYPE_IMAGE,
    NEWS_TYPE_VIDEO,
    NEWS_TYPE_OUTSIDE_LINK,
    NEWS_LIST_IMAGE,
    NEWS_CONTENT_IMAGE,
    NEWS_CATEGORY_COMMON,
    NEWS_CATEGORY_SEMINAR,
    NEWS_CATEGORY_ACTIVITY,
    NEWS_CATEGORY_H5_ACTIVITY,
    NEWS_CATEGORY_REVELATION,
    NEWS_CATEGORY_ADVERT,
    GLOBAL_TOP_NEWS_LIST,
    TOP_NEWS_LIST,
    SORT_NEWS_LIST,
    COMMON_NEWS_LIST,
    GLOBAL_TOP_NEWS_LIST_COUNT,
    TOP_NEWS_LIST_COUNT,
    SORT_NEWS_LIST_COUNT,
    COMMON_NEWS_LIST_COUNT,
    MATERIAL_LIST_COUNT,
    CMS_COLLECTION_NAME_PREFIX,
    COUNTRY_SITE_ID,
    ONLINE_COUNTRY_REGION_ID,
    LOCAL_CHANNEL_TAG,
    COUNTRY_CHANNEL_TAG,
    REDIS_KEY_NEWS_DETAIL,
    REDIS_KEY_MATERIAL_LIST,
    REDIS_KEY_ARTICLE_DETAIL,
    REDIS_KEY_GLOBAL_YOP_LIST,
    REDIS_KEY_TOP_LIST,
    REDIS_KEY_SORT_LIST,
    REDIS_EXPIRE_NEWS_DETAIL,
    REDIS_EXPIRE_MATERIAL_LIST,
    MATERIAL_LIST_CHOOSE_DEFAULT,
    UN_PUBLISHED_ARTICLE,
    PUBLISHED_ARTICLE,
    PUSH_TO_USER,
    PUSH_TO_SITE,
    PUSH_TO_ALL,
    ONLINE_SET_TOP_ARTICLE,
    ONLINE_GLOBAL_ARTICLE,
    ONLINE_LOCAL_CHANNEL,
    ONLINE_COUNTRY_CHANNEL
};